from typing import Dict, Any, List

REAL_CONSTELLATIONS: Dict[str, Dict[str, Any]] = {
    "orion": {
        "label": "Orion",
        "points": [
            {"id": "betelgeuse", "x": 18, "y": 18, "rank": 1},
            {"id": "bellatrix", "x": 62, "y": 20, "rank": 2},
            {"id": "alnitak", "x": 38, "y": 42, "rank": 3},
            {"id": "alnilam", "x": 48, "y": 48, "rank": 4},
            {"id": "mintaka", "x": 58, "y": 54, "rank": 5},
            {"id": "saiph", "x": 34, "y": 78, "rank": 6},
            {"id": "rigel", "x": 70, "y": 76, "rank": 7},
        ],
        "connections": [(0, 2), (1, 4), (2, 3), (3, 4), (2, 5), (4, 6)],
    },
    "cassiopeia": {
        "label": "Cassiopeia",
        "points": [
            {"id": "c1", "x": 14, "y": 48, "rank": 1},
            {"id": "c2", "x": 30, "y": 26, "rank": 2},
            {"id": "c3", "x": 48, "y": 56, "rank": 3},
            {"id": "c4", "x": 66, "y": 28, "rank": 4},
            {"id": "c5", "x": 84, "y": 52, "rank": 5},
        ],
        "connections": [(0, 1), (1, 2), (2, 3), (3, 4)],
    },
    "ursa_major": {
        "label": "Ursa Major",
        "points": [
            {"id": "u1", "x": 18, "y": 30, "rank": 1},
            {"id": "u2", "x": 32, "y": 26, "rank": 2},
            {"id": "u3", "x": 46, "y": 34, "rank": 3},
            {"id": "u4", "x": 60, "y": 44, "rank": 4},
            {"id": "u5", "x": 72, "y": 50, "rank": 5},
            {"id": "u6", "x": 82, "y": 66, "rank": 6},
            {"id": "u7", "x": 62, "y": 70, "rank": 7},
        ],
        "connections": [(0, 1), (1, 2), (2, 3), (3, 4), (4, 5), (3, 6)],
    },
    "cygnus": {
        "label": "Cygnus",
        "points": [
            {"id": "cy1", "x": 50, "y": 16, "rank": 1},
            {"id": "cy2", "x": 50, "y": 36, "rank": 2},
            {"id": "cy3", "x": 50, "y": 58, "rank": 3},
            {"id": "cy4", "x": 50, "y": 80, "rank": 4},
            {"id": "cy5", "x": 24, "y": 42, "rank": 5},
            {"id": "cy6", "x": 76, "y": 42, "rank": 6},
        ],
        "connections": [(0, 1), (1, 2), (2, 3), (1, 4), (1, 5)],
    },
    "lyra": {
        "label": "Lyra",
        "points": [
            {"id": "l1", "x": 22, "y": 36, "rank": 1},
            {"id": "l2", "x": 48, "y": 18, "rank": 2},
            {"id": "l3", "x": 72, "y": 36, "rank": 3},
            {"id": "l4", "x": 58, "y": 64, "rank": 4},
            {"id": "l5", "x": 34, "y": 62, "rank": 5},
        ],
        "connections": [(0, 1), (1, 2), (2, 3), (3, 4), (4, 0)],
    },
    "gemini": {
        "label": "Gemini",
        "points": [
            {"id": "g1", "x": 28, "y": 18, "rank": 1},
            {"id": "g2", "x": 36, "y": 38, "rank": 2},
            {"id": "g3", "x": 42, "y": 58, "rank": 3},
            {"id": "g4", "x": 48, "y": 78, "rank": 4},
            {"id": "g5", "x": 62, "y": 20, "rank": 5},
            {"id": "g6", "x": 66, "y": 40, "rank": 6},
            {"id": "g7", "x": 72, "y": 60, "rank": 7},
            {"id": "g8", "x": 78, "y": 80, "rank": 8},
        ],
        "connections": [(0, 1), (1, 2), (2, 3), (4, 5), (5, 6), (6, 7)],
    },
    "leo": {
        "label": "Leo",
        "points": [
            {"id": "le1", "x": 18, "y": 36, "rank": 1},
            {"id": "le2", "x": 34, "y": 24, "rank": 2},
            {"id": "le3", "x": 50, "y": 36, "rank": 3},
            {"id": "le4", "x": 64, "y": 52, "rank": 4},
            {"id": "le5", "x": 76, "y": 68, "rank": 5},
            {"id": "le6", "x": 48, "y": 62, "rank": 6},
        ],
        "connections": [(0, 1), (1, 2), (2, 3), (3, 4), (2, 5)],
    },
    "scorpius": {
        "label": "Scorpius",
        "points": [
            {"id": "s1", "x": 22, "y": 20, "rank": 1},
            {"id": "s2", "x": 34, "y": 32, "rank": 2},
            {"id": "s3", "x": 44, "y": 46, "rank": 3},
            {"id": "s4", "x": 52, "y": 60, "rank": 4},
            {"id": "s5", "x": 60, "y": 72, "rank": 5},
            {"id": "s6", "x": 76, "y": 80, "rank": 6},
            {"id": "s7", "x": 70, "y": 60, "rank": 7},
        ],
        "connections": [(0, 1), (1, 2), (2, 3), (3, 4), (4, 5), (4, 6)],
    },
    "taurus": {
        "label": "Taurus",
        "points": [
            {"id": "t1", "x": 18, "y": 48, "rank": 1},
            {"id": "t2", "x": 36, "y": 30, "rank": 2},
            {"id": "t3", "x": 56, "y": 28, "rank": 3},
            {"id": "t4", "x": 74, "y": 46, "rank": 4},
            {"id": "t5", "x": 52, "y": 54, "rank": 5},
        ],
        "connections": [(0, 1), (1, 2), (2, 3), (2, 4)],
    },
    "aries": {
        "label": "Aries",
        "points": [
            {"id": "a1", "x": 22, "y": 34, "rank": 1},
            {"id": "a2", "x": 48, "y": 44, "rank": 2},
            {"id": "a3", "x": 74, "y": 56, "rank": 3},
        ],
        "connections": [(0, 1), (1, 2)],
    },
    "aquarius": {
        "label": "Aquarius",
        "points": [
            {"id": "aq1", "x": 18, "y": 30, "rank": 1},
            {"id": "aq2", "x": 34, "y": 42, "rank": 2},
            {"id": "aq3", "x": 48, "y": 32, "rank": 3},
            {"id": "aq4", "x": 62, "y": 50, "rank": 4},
            {"id": "aq5", "x": 76, "y": 40, "rank": 5},
            {"id": "aq6", "x": 84, "y": 60, "rank": 6},
        ],
        "connections": [(0, 1), (1, 2), (2, 3), (3, 4), (4, 5)],
    },
    "virgo": {
        "label": "Virgo",
        "points": [
            {"id": "v1", "x": 20, "y": 24, "rank": 1},
            {"id": "v2", "x": 36, "y": 36, "rank": 2},
            {"id": "v3", "x": 48, "y": 50, "rank": 3},
            {"id": "v4", "x": 64, "y": 62, "rank": 4},
            {"id": "v5", "x": 80, "y": 74, "rank": 5},
            {"id": "v6", "x": 56, "y": 30, "rank": 6},
        ],
        "connections": [(0, 1), (1, 2), (2, 3), (3, 4), (1, 5)],
    },
    "sagittarius": {
        "label": "Sagittarius",
        "points": [
            {"id": "sg1", "x": 24, "y": 34, "rank": 1},
            {"id": "sg2", "x": 40, "y": 24, "rank": 2},
            {"id": "sg3", "x": 54, "y": 36, "rank": 3},
            {"id": "sg4", "x": 68, "y": 24, "rank": 4},
            {"id": "sg5", "x": 74, "y": 48, "rank": 5},
            {"id": "sg6", "x": 58, "y": 62, "rank": 6},
            {"id": "sg7", "x": 40, "y": 58, "rank": 7},
        ],
        "connections": [(0, 1), (1, 2), (2, 3), (2, 4), (2, 5), (5, 6)],
    },
    "capricornus": {
        "label": "Capricornus",
        "points": [
            {"id": "cp1", "x": 18, "y": 46, "rank": 1},
            {"id": "cp2", "x": 36, "y": 28, "rank": 2},
            {"id": "cp3", "x": 58, "y": 34, "rank": 3},
            {"id": "cp4", "x": 78, "y": 56, "rank": 4},
            {"id": "cp5", "x": 54, "y": 66, "rank": 5},
        ],
        "connections": [(0, 1), (1, 2), (2, 3), (2, 4), (4, 0)],
    },
    "pisces": {
        "label": "Pisces",
        "points": [
            {"id": "p1", "x": 20, "y": 30, "rank": 1},
            {"id": "p2", "x": 34, "y": 44, "rank": 2},
            {"id": "p3", "x": 46, "y": 60, "rank": 3},
            {"id": "p4", "x": 62, "y": 48, "rank": 4},
            {"id": "p5", "x": 78, "y": 34, "rank": 5},
            {"id": "p6", "x": 70, "y": 68, "rank": 6},
        ],
        "connections": [(0, 1), (1, 2), (2, 3), (3, 4), (3, 5)],
    },
    "canis_major": {
        "label": "Canis Major",
        "points": [
            {"id": "cm1", "x": 18, "y": 52, "rank": 1},
            {"id": "cm2", "x": 36, "y": 34, "rank": 2},
            {"id": "cm3", "x": 52, "y": 42, "rank": 3},
            {"id": "cm4", "x": 68, "y": 56, "rank": 4},
            {"id": "cm5", "x": 82, "y": 74, "rank": 5},
        ],
        "connections": [(0, 1), (1, 2), (2, 3), (3, 4)],
    },
    "canis_minor": {
        "label": "Canis Minor",
        "points": [
            {"id": "cmi1", "x": 24, "y": 42, "rank": 1},
            {"id": "cmi2", "x": 72, "y": 52, "rank": 2},
        ],
        "connections": [(0, 1)],
    },
    "delphinus": {
        "label": "Delphinus",
        "points": [
            {"id": "d1", "x": 26, "y": 48, "rank": 1},
            {"id": "d2", "x": 42, "y": 28, "rank": 2},
            {"id": "d3", "x": 62, "y": 34, "rank": 3},
            {"id": "d4", "x": 70, "y": 56, "rank": 4},
            {"id": "d5", "x": 48, "y": 66, "rank": 5},
        ],
        "connections": [(0, 1), (1, 2), (2, 3), (3, 4), (4, 0)],
    },
    "pegasus": {
        "label": "Pegasus",
        "points": [
            {"id": "pg1", "x": 24, "y": 24, "rank": 1},
            {"id": "pg2", "x": 72, "y": 24, "rank": 2},
            {"id": "pg3", "x": 72, "y": 72, "rank": 3},
            {"id": "pg4", "x": 24, "y": 72, "rank": 4},
            {"id": "pg5", "x": 86, "y": 46, "rank": 5},
        ],
        "connections": [(0, 1), (1, 2), (2, 3), (3, 0), (1, 4)],
    },
    "bootes": {
        "label": "Boötes",
        "points": [
            {"id": "b1", "x": 24, "y": 20, "rank": 1},
            {"id": "b2", "x": 42, "y": 34, "rank": 2},
            {"id": "b3", "x": 56, "y": 50, "rank": 3},
            {"id": "b4", "x": 70, "y": 68, "rank": 4},
            {"id": "b5", "x": 38, "y": 66, "rank": 5},
        ],
        "connections": [(0, 1), (1, 2), (2, 3), (2, 4)],
    },
}

SECTOR_CONSTELLATION_PREFERENCES: Dict[str, List[str]] = {
    "energy": ["orion", "scorpius", "taurus"],
    "technology": ["cygnus", "lyra", "pegasus"],
    "healthcare": ["gemini", "delphinus", "virgo"],
    "finance": ["cassiopeia", "leo", "bootes"],
    "consumer": ["ursa_major", "pisces", "aquarius"],
    "industrials": ["capricornus", "canis_major", "sagittarius"],
    "real_assets": ["canis_minor", "taurus", "leo"],
    "general": ["cassiopeia", "aquarius", "pegasus"],
}
